https://s3.amazonaws.com/heroku-buildpack-ruby: https://d3nlvu62nhllo4.cloudfront.net
https://s3-eu-west-1.amazonaws.com/dotcloudapp.com.packages/buildpack-ruby: https://s3.amazonaws.com/dotcloudapp.com.packages/buildpack-ruby
https://s3-eu-west-1.amazonaws.com/dotcloudapp.com.packages/buildpack-java: https://s3.amazonaws.com/dotcloudapp.com.packages/buildpack-java
